import { apiKey } from '.';

export const url = {
    // FREE - DOWNLOADER
    facebookScraper: (link: string): string => `https://api.i-tech.id/dl/fb?key=${apiKey}&link=${link}`,
    youtubeScraper: (link: string): string => `https://api.i-tech.id/dl/yt?key=${apiKey}&link=${link}`,
    pinterestScraper: (link: string): string => `https://api.i-tech.id/dl/pin?key=${apiKey}&link=${link}`,
    instagramScraper: (link: string): string => `https://api.i-tech.id/dl/igdl?key=${apiKey}&link=${link}`,
    // FREE - ANIME
    randomQuotesAnime: (): string => `https://api.i-tech.id/anim/quotes?key=${apiKey}`,
    randomWibu: (): string => `https://api.i-tech.id/anim/wibu?key=${apiKey}`,
    randomNekonime: (): string => `https://api.i-tech.id/anim/nime?key=${apiKey}`,
    randomNekonime2: (): string => `https://api.i-tech.id/anim/nime2?key=${apiKey}`,
    randomAnime: (): string => `https://api.i-tech.id/anim/anime?key=${apiKey}`,
    randomAnime2: (): string => `https://api.i-tech.id/anim/anime2?key=${apiKey}`,
    randomAnimeHentai: (): string => `https://api.i-tech.id/anim/hentai?key=${apiKey}`,
    randomAnimeYuri: (): string => `https://api.i-tech.id/anim/yuri?key=${apiKey}`,
    randomAnimeDVA: (): string => `https://api.i-tech.id/anim/dva?key=${apiKey}`,
    randomAnimeTrap: (): string => `https://api.i-tech.id/anim/trap?key=${apiKey}`,
    randomAnimeHug: (): string => `https://api.i-tech.id/anim/hug?key=${apiKey}`,
    randomAnimeNsfwNeko: (): string => `https://api.i-tech.id/anim/nsfwneko?key=${apiKey}`,
    randomAnimeBaguette: (): string => `https://api.i-tech.id/anim/baguette?key=${apiKey}`,
    jurnalOtaku: (type: string, query: string): string => `https://api.i-tech.id/anim/otaku?key=${apiKey}&type=${type}&query=${query}`,
    dewaBatchScraper: (query: string): string => `https://api.i-tech.id/anim/dewabatch?key=${apiKey}&query=${query}`,
    kusonimeScraper: (query: string): string => `https://api.i-tech.id/anim/kusonime?key=${apiKey}&query=${query}`,
    // FREE - ENCRYPT
    encryptBcrypt: (string: string): string => `https://api.i-tech.id/hash/bcrypt?key=${apiKey}&string=${string}`,
    encryptSHA: (type:string, string: string): string => `https://api.i-tech.id/hash/sha?key=${apiKey}&type=${type}&string=${string}`,
    encryptBase32: (type:string, string: string): string => `https://api.i-tech.id/hash/bs32?key=${apiKey}&type=${type}&string=${string}`,
    encryptBase64: (type:string, string: string): string => `https://api.i-tech.id/hash/bs64?key=${apiKey}&type=${type}&string=${string}`,
    // FREE - TOOLS
    toolsJamDunia: (kota: string): string => `https://api.i-tech.id/tools/jam?key=${apiKey}&kota=${kota}`,
    toolsChordGuitar: (query: string): string => `https://api.i-tech.id/tools/chord?key=${apiKey}&query=${query}`,
    toolsCuacaDunia: (kota: string): string => `https://api.i-tech.id/tools/cuaca?key=${apiKey}&kota=${kota}`,
    toolsArtiNama: (nama: string): string => `https://api.i-tech.id/tools/arti?key=${apiKey}&nama=${nama}`,
    toolsKataAlay: (kata: string): string => `https://api.i-tech.id/tools/alay?key=${apiKey}&kata=${kata}`,
    toolsKataHilih: (kata: string): string => `https://api.i-tech.id/tools/hilih?key=${apiKey}&kata=${kata}`,
    toolsKataNinja: (kata: string): string => `https://api.i-tech.id/tools/ninja?key=${apiKey}&kata=${kata}`,
    toolsRandomQuotes1: (): string => `https://api.i-tech.id/tools/quotes?key=${apiKey}`,
    toolsRandomQuotes2: (): string => `https://api.i-tech.id/tools/quotes2?key=${apiKey}`,
    toolsRandomQuotes3: (): string => `https://api.i-tech.id/tools/quotes3?key=${apiKey}`,
    toolsRandomNama: (gender: string): string => `https://api.i-tech.id/tools/nama?key=${apiKey}&gender=${gender}`,
    toolsSearchLirik: (query: string): string => `https://api.i-tech.id/tools/lirik?key=${apiKey}&query=${query}`,
    toolsJadwalSholat: (kota: string): string => `https://api.i-tech.id/tools/sholat?key=${apiKey}&kota=${kota}`,
    toolsGempaTerkini: (): string => `https://api.i-tech.id/tools/bmkg?key=${apiKey}`,
    toolsUrlShortener: (link: string): string => `https://api.i-tech.id/tools/shorturl?key=${apiKey}&link=${link}`,
    toolsScreenshotWebsite: (link: string): string => `https://api.i-tech.id/tools/ssweb?key=${apiKey}&link=${link}`,
    toolsAnimalFacts: (animal: string): string => `https://api.i-tech.id/tools/fact?key=${apiKey}&animal=${animal}`,
    toolsRandomAsu: (): string => `https://api.i-tech.id/tools/asu?key=${apiKey}`,
    toolsRandomRubah: (): string => `https://api.i-tech.id/tools/foxes?key=${apiKey}`,
    toolsRandomKambing: (): string => `https://api.i-tech.id/tools/goat?key=${apiKey}`,
    toolsRandomKucing: (): string => `https://api.i-tech.id/tools/cat?key=${apiKey}`,
    toolsRandomAnjing: (): string => `https://api.i-tech.id/tools/dog?key=${apiKey}`,
    toolsQrCodeMaker: (query: string): string => `https://api.i-tech.id/tools/qr?key=${apiKey}&query=${query}`,
    toolsFaktaUnik: (): string => `https://api.i-tech.id/tools/fakta?key=${apiKey}`,
    toolsPantunPakboy: (): string => `https://api.i-tech.id/tools/pantun?key=${apiKey}`,
    toolsKbbiScraper: (query: string): string => `https://api.i-tech.id/tools/kbbi?key=${apiKey}&query=${query}`,
    toolsRandomPanda: (): string => `https://api.i-tech.id/tools/panda?key=${apiKey}`,
    toolsRandomPandaMerah: (): string => `https://api.i-tech.id/tools/pandar?key=${apiKey}`,
    toolsRandomGambarBurung: (): string => `https://api.i-tech.id/tools/bird?key=${apiKey}`,
    toolsRandomGambarTupai: (): string => `https://api.i-tech.id/tools/fox?key=${apiKey}`,
    toolsRandomGambarKoala: (): string => `https://api.i-tech.id/tools/koala?key=${apiKey}`,
    toolsRandomGifWink: (): string => `https://api.i-tech.id/tools/wink?key=${apiKey}`,
    toolsRandomGifPat: (): string => `https://api.i-tech.id/tools/pat?key=${apiKey}`,
    toolsRandomGifHug: (): string => `https://api.i-tech.id/tools/hug?key=${apiKey}`,
    // PREMIUM - DOWNLOADER
    premiumTiktokScraper: (link: string): string => `https://api.i-tech.id/dl/tiktok?key=${apiKey}&link=${link}`,
    premiumTiktokStalker: (query: string): string => `https://api.i-tech.id/dl/tiktoks?key=${apiKey}&query=${query}`,
    premiumYoutubeSearch: (query: string): string => `https://api.i-tech.id/dl/yts?key=${apiKey}&query=${query}`,
    premiumInstagramStalker: (username: string): string => `https://api.i-tech.id/dl/stalk?key=${apiKey}&username=${username}`,
    premiumSmuleScraper: (link: string): string => `https://api.i-tech.id/dl/smule?key=${apiKey}&link=${link}`,
    premiumSmuleStalker: (username: string): string => `https://api.i-tech.id/dl/smules?key=${apiKey}&username=${username}`,
    premiumTimelineScraper: (link: string): string => `https://api.i-tech.id/dl/timeline?key=${apiKey}&link=${link}`,
    premiumTwitterVideoScraper: (link: string): string => `https://api.i-tech.id/dl/twitter?key=${apiKey}&link=${link}`,
    premiumYoutubePlayMusic: (query: string): string => `https://api.i-tech.id/dl/ytplay?key=${apiKey}&query=${query}`,
    premiumMediafireScraper: (link: string): string => `https://api.i-tech.id/dl/mediafire?key=${apiKey}&link=${link}`,
    premiumCocofunVideoScraper: (link: string): string => `https://api.i-tech.id/dl/cocofun?key=${apiKey}&link=${link}`,
    premiumSnackVideoScraper: (link: string): string => `https://api.i-tech.id/dl/snackdl?key=${apiKey}&link=${link}`,
    premiumPlayStoreDownloader: (link: string): string => `https://api.i-tech.id/dl/psdl?key=${apiKey}&link=${link}`,
    premiumUpToDownScraper: (query: string): string => `https://api.i-tech.id/dl/utdl?key=${apiKey}&query=${query}`,
    premiumApkPureScraper: (query: string): string => `https://api.i-tech.id/dl/apkpure?key=${apiKey}&query=${query}`,
    // PREMIUM - TOOLS
    premiumBrainly: (query: string): string => `https://api.i-tech.id/tools/brainly?key=${apiKey}&query=${query}`,
    premiumRamalanJodoh: (p1: string, p2: string): string => `https://api.i-tech.id/tools/jodoh?key=${apiKey}&p1=${p1}&p2=${p2}`,
    premiumQuotesMaker: (type: string, author: string, kata: string): string => `https://api.i-tech.id/tools/qtm?key=${apiKey}&type=${type}&author=${author}&text=${kata}`,
    premiumTextToSpeech: (query: string): string => `https://api.i-tech.id/tools/tts?key=${apiKey}&query=${query}`,
    premiumWikipediaScraper: (query: string): string => `https://api.i-tech.id/tools/wiki?key=${apiKey}&query=${query}`,
    premiumJadwalTv: (list: string): string => `https://api.i-tech.id/tools/jadwaltv?key=${apiKey}&list=${list}`,
    premiumCekJodoh: (query: string): string => `https://api.i-tech.id/tools/cekjodoh?key=${apiKey}&query=${query}`,
    premiumGoogleTranslate: (lang: string, teks: string): string => `https://api.i-tech.id/tools/gambar?key=${apiKey}&lang=${lang}&teks=${teks}`,
    premiumHartaTahta: (kata: string): string => `https://api.i-tech.id/tools/harta?key=${apiKey}&kata=${kata}`,
    premiumPUBGMaker: (teks1: string, teks2: string): string => `https://api.i-tech.id/tools/pubg?key=${apiKey}&teks1=${teks1}&teks2=${teks2}`,
    premiumAvengerMaker: (teks1: string, teks2: string): string => `https://api.i-tech.id/tools/avenger?key=${apiKey}&teks1=${teks1}&teks2=${teks2}`,
    premiumHahaMaker: (teks1: string, teks2: string): string => `https://api.i-tech.id/tools/haha?key=${apiKey}&teks1=${teks1}&teks2=${teks2}`,
    premiumMarvelMaker1: (teks1: string, teks2: string): string => `https://api.i-tech.id/tools/marvel?key=${apiKey}&teks1=${teks1}&teks2=${teks2}`,
    premiumMarvelrMaker2: (teks1: string, teks2: string): string => `https://api.i-tech.id/tools/marvel2?key=${apiKey}&teks1=${teks1}&teks2=${teks2}`,
    premiumSuitGames: (query: string): string => `https://api.i-tech.id/tools/suit?key=${apiKey}&query=${query}`,
    premiumSarangheoGenerator: (teks: string): string => `https://api.i-tech.id/tools/sh?key=${apiKey}&teks=${teks}`,
    premiumGoogleScreenshot: (teks1: string, teks2: string, teks3: string): string => `https://api.i-tech.id/tools/gs?key=${apiKey}&teks1=${teks1}&teks2=${teks2}&teks3=${teks3}`,
    premiumFaceIdentify: (link: string): string => `https://api.i-tech.id/tools/fm?key=${apiKey}&link=${link}`,
    premiumRainbowMaker: (url: string): string => `https://api.i-tech.id/tools/rainbow?key=${apiKey}&url=${url}`,
    premiumGlassMaker: (url: string): string => `https://api.i-tech.id/tools/glass?key=${apiKey}&url=${url}`,
    premiumWastedMaker: (url: string): string => `https://api.i-tech.id/tools/wasted?key=${apiKey}&url=${url}`,
    premiumTriggeredMaker: (url: string): string => `https://api.i-tech.id/tools/triggered?key=${apiKey}&url=${url}`,
    premiumYoutubeCommand: (nama: string, komen: string, url: string): string => `https://api.i-tech.id/tools/ytc?key=${apiKey}&nama=${nama}&komen=${komen}&url=${url}`,
    premiumRemoveBg2: (url: string): string => `https://api.i-tech.id/tools/nobg2?key=${apiKey}&url=${url}`,
    premiumJadwalTv2: (channel: string): string => `https://api.i-tech.id/tools/jadwaltv2?key=${apiKey}&channel=${channel}`,
    premiumRandomMemeGenerator: (): string => `https://api.i-tech.id/tools/meme?key=${apiKey}`,
    premiumCekHalalMui: (query: string): string => `https://api.i-tech.id/tools/mui?key=${apiKey}&query=${query}`,
    premiumPageTranslator: (link: string): string => `https://api.i-tech.id/tools/ptrans?key=${apiKey}&link=${link}`,
    premiumPhotomathScraper: (link: string): string => `https://api.i-tech.id/tools/photomath?key=${apiKey}&link=${link}`,
    // VIP - DOWNLOADER
    vipInstagramStory: (username: string): string => `https://api.i-tech.id/dl/story?key=${apiKey}&username=${username}`,
    vipInstagramHighlight: (username: string): string => `https://api.i-tech.id/dl/highlight?key=${apiKey}&username=${username}`,
    vipInstagramTv: (username: string): string => `https://api.i-tech.id/dl/igtv?key=${apiKey}&username=${username}`,
    vipInstagramHashtag: (query: string): string => `https://api.i-tech.id/dl/story?key=${apiKey}&query=${query}`,
    vipGoogleSearch: (query: string): string => `https://api.i-tech.id/dl/googles?key=${apiKey}&query=${query}`,
    vipPlayStore: (query: string): string => `https://api.i-tech.id/dl/ps?key=${apiKey}&query=${query}`,
    vipJooxScraper: (query: string): string => `https://api.i-tech.id/dl/joox?key=${apiKey}&query=${query}`,
    vipSpotifyScraper: (query: string): string => `https://api.i-tech.id/dl/spotify?key=${apiKey}&query=${query}`,
    // vipPornhubScraper: (link: string): string => `https://api.i-tech.id/dl/pornhub?key=${apiKey}&link=${link}`,
    // vipPornhubStalker: (username: string): string => `https://api.i-tech.id/dl/phs?key=${apiKey}&username=${username}`,
    // VIP - TOOLS
    vipCekResi: (kurir: string, resi: string): string => `https://api.i-tech.id/tools/resi?key=${apiKey}&kurir=${kurir}&resi=${resi}`,
    vipTulisDiBuku: (text: string): string => `https://api.i-tech.id/tools/nulis?key=${apiKey}&text=${text}`,
    vipGenerateCoolText: (text: string): string => `https://api.i-tech.id/tools/cool?key=${apiKey}&text=${text}`,
    vipPrediksiUmur: (nama: string): string => `https://api.i-tech.id/tools/umur?key=${apiKey}&nama=${nama}`,
    vipMacAddresLookup: (mac: string): string => `https://api.i-tech.id/tools/mac?key=${apiKey}&mac=${mac}`,
    vipCekZodiak: (nama: string, tgl: string): string => `https://api.i-tech.id/tools/zodiak?key=${apiKey}&nama=${nama}&tgl=${tgl}`,
    vipAlQuran: (surat: string): string => `https://api.i-tech.id/tools/quran?key=${apiKey}&surat=${surat}`,
    vipSimiSimi: (lang: string, kata: string): string => `https://api.i-tech.id/tools/simi?key=${apiKey}&lang=${lang}&kata=${kata}`,
    vipRemoveBg: (link: string): string => `https://api.i-tech.id/tools/nobg?key=${apiKey}&link=${link}`,
    vipHartaTahtaCostume: (teks1: string, teks2: string, teks3: string): string => `https://api.i-tech.id/tools/harta?key=${apiKey}&teks1=${teks1}&teks2=${teks2}&teks3=${teks3}`,
    vipWhatsappSender: (nomor: string, teks: string): string => `https://api.i-tech.id/tools/otp?key=${apiKey}&nomor=${nomor}&teks=${teks}`,
    vip8dAudioBooster: (link: string): string => `https://api.i-tech.id/tools/8d?key=${apiKey}&link=${link}`
}